# Generated by Django 3.1.4 on 2021-03-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Npi',
        ),
    ]
